__asm__(
".text\n"
".global " START "\n"
".type " START ",%function\n"
START ":\n"
"C.BSTART.STD\n"
"c.movr\tsp,\t->a0\n"
".weak _DYNAMIC\n"
".hidden _DYNAMIC\n"
"addtpc\t_DYNAMIC,\t->a1\n"
"addi\ta1,\t_DYNAMIC,\t->a1\n"
"BSTART\tCALL, " START "_c, ra=1f\n"
"C.BSTOP\n"
"1:\n"
"C.BSTART\tDIRECT, 1b\n"
"C.BSTOP\n"
);
