__asm__(
".text\n"
".global " START "\n"
".type " START ",%function\n"
START ":\n"
"C.BSTART.STD\n"
"c.movr\tsp,\t->a0\n"
".weak _DYNAMIC\n"
".hidden _DYNAMIC\n"
"addtpc\t%tpcrel_hi(_DYNAMIC),\t->a1\n"
"addi\ta1,\t%tpcrel_lo(_DYNAMIC),\t->a1\n"
"HL.BSTART.STD\tCALL, " START "_c, ra=1f\n"
"C.BSTOP\n"
"1:\n"
"C.BSTART\tDIRECT, 1b\n"
"C.BSTOP\n"
);
