__asm__(
"	.text\n"
"	.globl	_start\n"
"	.type	_start,@function\n"
"	.align 1\n"
"_start:	\n"
"	C.BSTART\n"
"	addi	sp, 0, ->t\n"
"	addi	t#1, 0, ->t\n"
"	addi	t#1, 0, ->a0\n"
"   .Lpcrel_hi1:\n"
"	C.BSTART\n"
"	1:\n"
"	addtpc	%tpcrel_hi(.Lpcrel_hi1), ->t\n"
"	addi	t#1, %tpcrel_lo(1b), ->t\n"
"	addi	a1, 0, ->t\n"
"	add	    t#1, t#2, ->t\n"
"	addi	t#1, 0, ->a1\n"
"	addi	sp, 0, ->t\n"
"	andi	t#1, -16, ->t\n"
"	addi	t#1, 0, ->sp\n"
"	BSTART DIRECT	_start_c\n"
);